- name: Install python3-cerberus
  pip:
    name: cerberus
    executable: pip3
    state: latest

- name: pip self-update
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Install python3-kafka
  pip:
    name: kafka-python
    executable: pip3
    state: latest

- name: Link yaml
  file:
    src: "/usr/lib/python3/dist-packages/yaml"
    dest: "/etc/aminer/conf-enabled/yaml"
    state: link
