- name: Install python3-cerberus
  pip:
    name: cerberus
    executable: pip3
    state: latest

- name: Install python3-kafka
  pip:
    name: kafka-python
    executable: pip3
    state: latest

- name: Find cerberus
  find:
    paths: "/usr"
    patterns: 'cerberus'
    file_type: 'directory'
  register: cerberus

- name: Link cerberus
  file:
    src: "{{ item.path }}"
    dest: "/etc/aminer/conf-enabled/{{item.path.split('/')[-1]}}"
    state: link
  with_items: "{{cerberus.files }}"


- name: Link kafka
  file:
    src: "{{aminer_pippath}}/kafka"
    dest: /etc/aminer/conf-enabled/kafka
    state: link

