- name: Install python3-cerberus
  pip:
    name: cerberus
    executable: pip3
    state: latest

- name: pip self-update
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Install python3-kafka
  pip:
    name: kafka-python
    executable: pip3
    state: latest

- name: Find json.cpython
  find:
    paths: "/usr"
    patterns: 'json.cpython*.so'
    recurse: yes
  register: orjson

- name: Link orjson
  file:
    src: "{{ item.path }}"
    dest: "/etc/aminer/conf-enabled/{{item.path.split('/')[-1]}}"
    state: link
  with_items: "{{orjson.files }}"

- name: Find cerberus
  find:
    paths: "/usr"
    patterns: 'cerberus'
    file_type: 'directory'
    recurse: yes
  register: cerberus

- name: Link cerberus
  file:
    src: "{{ item.path }}"
    dest: "/etc/aminer/conf-enabled/{{item.path.split('/')[-1]}}"
    state: link
  with_items: "{{cerberus.files }}"

- name: Find kafka
  find:
    paths: "/usr"
    patterns: 'kafka'
    file_type: 'directory'
    recurse: yes
  register: kafka

- name: Link kafka
  file:
    src: "{{ item.path }}"
    dest: "/etc/aminer/conf-enabled/{{item.path.split('/')[-1]}}"
    state: link
  with_items: "{{kafka.files }}"


