- name: pip self-update
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Install python3-cerberus
  pip:
    name: cerberus
    executable: pip3
    state: latest

- name: Install python3-kafka
  pip:
    name: kafka-python
    executable: pip3
    state: latest

- name: Install importlib-metadata
  pip:
    name: importlib-metadata
    executable: pip3
    state: latest
