- name: pip self-update
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Install python3-cerberus
  pip:
    name: cerberus
    executable: pip3
    state: latest

- name: Install python3-kafka
  pip:
    name: kafka-python
    executable: pip3
    state: latest

- name: Install importlib-metadata
  pip:
    name: importlib-metadata
    executable: pip3
    state: latest

- name: Find importlib-metadata
  find:
    paths: "/usr"
    patterns: 'importlib_metadata'
    recurse: yes
    file_type: "directory"
  register: importlib

- name: Link importlib-metadata
  file:
    src: "{{ item.path }}"
    dest: "/etc/aminer/conf-enabled/{{item.path.split('/')[-1]}}"
    state: link
  with_items: "{{importlib.files }}"

- name: Find zipp
  find:
    paths: "/usr"
    patterns: 'zipp'
    recurse: yes
    file_type: "directory"
  register: zipp

- name: Link zipp
  file:
    src: "{{ item.path }}"
    dest: "/etc/aminer/conf-enabled/{{item.path.split('/')[-1]}}"
    state: link
  with_items: "{{zipp.files }}"

- name: Find typing-extensions
  find:
    paths: "/usr"
    patterns: 'typing_extensions.py'
    recurse: yes
  register: typing

- name: Link typing-extensions
  file:
    src: "{{ item.path }}"
    dest: "/etc/aminer/conf-enabled/{{item.path.split('/')[-1]}}"
    state: link
  with_items: "{{typing.files }}"
