- name: RedHat copy Python Packages
  copy:
    src: /usr/lib64/python3.9/site-packages/
    dest: /usr/lib/python3.9/site-packages/
    remote_src: yes
    directory_mode:
  when: ansible_distribution == "RedHat"

- name: RedHat Link Python Packages
  command: ls /usr/lib/python3.9/site-packages
  when: ansible_distribution == "RedHat"

- name: Install python3-cerberus
  pip:
    name: cerberus
    executable: pip3
    state: latest

- name: pip self-update
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Install python3-kafka
  pip:
    name: kafka-python
    executable: pip3
    state: latest

- name: Install python3-pandas
  pip:
    name: pandas
    executable: pip3
    state: latest

- name: Install python3-patsy
  pip:
    name: patsy
    executable: pip3
    state: latest

- name: Install python3-statsmodels
  pip:
    name: statsmodels
    executable: pip3
    state: latest
