- name: pip self-update
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Install python3-kafka
  pip:
    name: kafka-python
    executable: pip3
    state: latest

- name: Install python3-patsy
  pip:
    name: patsy
    executable: pip3
    state: latest

- name: Install python3-statsmodels
  pip:
    name: statsmodels
    executable: pip3
    state: latest

- name: Link yaml
  file:
    src: "{{aminer_pythonpath[1]}}/yaml"
    dest: "/etc/aminer/conf-enabled/yaml"
    state: link
